version: '3'

services:
  web:
    build: .
    command: gunicorn citblock.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/static
    env_file:
      - ./.env.prod
    expose:
      - 8000
    depends_on: 
      - database
  database:
    image: postgres:12.0-alpine
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.prod
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pg_pass
      - POSTGRES_DB=postgres_prod
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/static
    ports:
      - 80:80
    depends_on:
      - web
volumes:
  postgres_data:
  static_volume: